# Be sure to change these!
base_url = "https://richardpatching.com"
title = "Richard Patching"
description = "I'm Richard. Welcome to my personal site. I write games and tools in Rust and sometimes blog about it."
# Sass compilation is required
compile_sass = true

# Optional: enable tags
taxonomies = [
    {name = "tags"}
]

# Code highlighting
[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]

# One of: blue, green, orange, pink, red.
# Defaults to blue.
accent_color = "blue"

# One of: blue, dark, green, orange, pink, red.
# Enabling dark background will also modify primary font color
# to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "blue"

# The logo text - defaults to "Terminimal theme"
logo_text = "richard patching"

# The logo link - defaults to base_url.
#logo_home_link = "/take/me/away!"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Richard Patching"

# Copyright text in HTML format. If specified,
# entirely replaces default copyright and author.
copyright_html = "powered by&nbsp;<a href='https://getzola.org'>zola</a>&nbsp;🦀"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "home", url = "$BASE_URL"},

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "blog", url = "$BASE_URL/blog"},
    {name = "about me", url = "$BASE_URL/about"},
    {name = "projects", url = "$BASE_URL/projects"},

    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/patchfx", newtab = true},
]

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = true

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
# favicon = "/favicon.png"
# favicon_mimetype = "image/png"
